server:
  port: 9002

spring:

  # Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    url: jdbc:postgresql://database-2.crttgwzqvw36.ap-south-1.rds.amazonaws.com:5432/resort_db?currentSchema=sc_room&ssl=false
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  # Name of the Application
  application:
    name: ROOM-SERVICE
  graphql:
    cors:
      allowed-origins: http://localhost:3000,http://localhost:4000,https://main.d26bdakkr07ep9.amplifyapp.com,https://locus-frontend-admin.onrender.com
services:
  resort: http://RESORT-SERVICE/api/resort
#  #Zipkin conf
#  zipkin:
#    base-url: http://127.0.0.1:9411/

# Service Registry Properties
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://43.204.232.113:8761/eureka/
#   instance:
#     hostname: 43.204.232.113


